version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./hometask
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
